version: '3.8'

services:
  mysql:
    image: mysql:8.0.36
    container_name: dev-mysql8
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=${MYSQL_DEFAULT_USER}
      - MYSQL_PASSWORD=${MYSQL_DEFAULT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
     - ./mysql:/var/lib/mysql
    restart: always
    ports:
     - '3306:3306'
